Repository opendatalu/gouvlu, pull requests merged in 2018-02, with the labels that each got.

#56 New Crowdin translations
  gouvlu/translations/fr/LC_MESSAGES/gouvlu.po
Labels: in progress

#57 New Crowdin translations
  gouvlu/translations/fr/LC_MESSAGES/gouvlu.po
Labels: in progress

#58 New Crowdin translations
  gouvlu/theme/translations/fr/LC_MESSAGES/gouvlu.po
Labels: in progress

#54 Revert "improve build environment" changes to package-lock.json
  package-lock.json
Labels: in progress

#60 Fix modals positionning (fix #53)
  assets/less/widgets/mobile-menu.less
Labels: bug, in progress

#61 Follow upstream 1.3 cards changes
  .gitignore
  assets/less/admin.less
  assets/less/mixins.less
  assets/less/pages/dataset.less
  assets/less/widgets/cards.less
  gouvlu/theme/templates/dataset/card.html
  gouvlu/theme/templates/reuse/card.html
  gouvlu/theme/templates/sections/featured-datasets.html
  gouvlu/theme/templates/sections/latest-datasets.html
  requirements/install.pip
Labels: in progress, style, upstream changes

#59 Extra pages
  .circleci/config.yml
  assets/less/common/typography.less
  assets/less/pages/faq.less
  assets/less/theme.less
  docker-compose.yml
  docker/udata.cfg
  gouvlu/static/faq/integration/exemple-integration-blog-etalab.png
  gouvlu/static/faq/outils/800px-CartePOI.png
  gouvlu/static/faq/outils/800px-Evolutionbio.png
  gouvlu/static/faq/outils/800px-Inventaire_du_patrimoine_Poitou-Chatrentes.png
  gouvlu/static/faq/outils/800px-Inventaire_du_patrimoine_vecteurs.png
  gouvlu/static/faq/outils/800px-OSM-cadastre.png
  gouvlu/static/faq/outils/800px-TileMill.png
  gouvlu/static/faq/outils/Alluvial.png
  gouvlu/static/faq/outils/Dependencies.png
  gouvlu/static/faq/outils/Heatmap-salons-coiffure-paris-opendatasoft.png
  gouvlu/static/faq/outils/PAC2012.jpg
  gouvlu/templates/faq/base.html
  gouvlu/templates/faq/citizen.html
  gouvlu/templates/faq/developer.html
  gouvlu/templates/faq/home.html
  gouvlu/templates/faq/producer.html
  gouvlu/templates/faq/reuser.html
  gouvlu/templates/faq/system-integrator.html
  gouvlu/templates/publishing.html
  gouvlu/templates/strategy.html
  gouvlu/templates/usage.html
  gouvlu/theme/__init__.py
  gouvlu/theme/templates/terms.html
  gouvlu/theme/translations/gouvlu.pot
  gouvlu/translations/gouvlu.pot
  gouvlu/views.py
  requirements/develop.pip
  requirements/test.pip
  setup.py
  tests/conftest.py
  tests/test_statec_backend.py
  tests/test_theme.py
  tests/test_views.py
Labels: in progress

#65 New Crowdin translations
  gouvlu/theme/translations/fr/LC_MESSAGES/gouvlu.po
  gouvlu/translations/fr/LC_MESSAGES/gouvlu.po
Labels: in progress

#67 Update docker-compose run server command
  docker-compose.yml
Labels: in progress

#69 add env variables for proxy config behind firewall
  docker-compose.yml
Labels: in progress

#70 Remove data.gouv.fr references, adapt content and remove unused pictures
  gouvlu/static/faq/integration/exemple-integration-blog-etalab.png
  gouvlu/static/faq/outils/800px-CartePOI.png
  gouvlu/static/faq/outils/800px-Evolutionbio.png
  gouvlu/static/faq/outils/800px-Inventaire_du_patrimoine_Poitou-Chatrentes.png
  gouvlu/static/faq/outils/800px-Inventaire_du_patrimoine_vecteurs.png
  gouvlu/static/faq/outils/800px-OSM-cadastre.png
  gouvlu/static/faq/outils/800px-TileMill.png
  gouvlu/static/faq/outils/Alluvial.png
  gouvlu/static/faq/outils/Dependencies.png
  gouvlu/static/faq/outils/Heatmap-salons-coiffure-paris-opendatasoft.png
  gouvlu/static/faq/outils/PAC2012.jpg
  gouvlu/templates/faq/citizen.html
  gouvlu/templates/faq/developer.html
  gouvlu/templates/faq/home.html
  gouvlu/templates/faq/producer.html
  gouvlu/templates/faq/reuser.html
  gouvlu/templates/faq/system-integrator.html
Labels: in progress

#71 add right contact information
  setup.py
Labels: in progress
